defi-wonderland/balancer-v1-amm

foundry.toml
test/unit/BPool.t.sol
test/unit/Utils.sol

test: exitPool happy path

---

src/contracts/BNum.sol

feat: add unchecked to BNum functions

---

test/unit/BPool.t.sol

test: add unit tests for constructor and 'is' functions

---

test/unit/BPool.t.sol

test: add tests for finalize

---

test/unit/BPool.t.sol

test: add tests for gulp function

---

test/unit/BPool.t.sol

test: unit tests for bind function

---

test/unit/BPool.t.sol

test: add unit tests for unbind function

---

test/unit/BPool.t.sol

test: add unit tests for rebind function

---

foundry.toml
test/unit/BFactory.t.sol
test/unit/BPool.t.sol

test: suite improvements

---

test/unit/BFactory.t.sol
test/unit/BPool.t.sol
test/utils/Utils.sol

test: improving unit tests assumptions

---

src/contracts/BPool.sol
test/unit/BPool.t.sol

fix: revert in maxRatio

---

remappings.txt
src/contracts/BFactory.sol
src/contracts/BPool.sol
src/interfaces/IBFactory.sol
src/interfaces/IBPool.sol
test/integration/PoolSwap.t.sol
test/unit/BFactory.t.sol
test/unit/BPool.t.sol

feat: add interfaces

---

src/contracts/BCoWConst.sol
src/contracts/BCoWPool.sol
src/interfaces/IBCoWPool.sol

fix: add missing parts in IBCowPool

---

yarn.lock

chore: fixing dependabot alerts

---

README.md

feat: updating readme for BCoW AMM

---

src/contracts/BCoWPool.sol
src/contracts/BPool.sol

refactor: renaming onlyController to _modifier_ standard

---

package.json
test/manual-smock/MockBNum.sol
test/unit/BNum.t.sol
test/unit/BNum.tree

Closes BAL-133
Continuation of #122 but targetting `dev` branch.

test: adding BTT tests for BNum (cont. #122)

---

.github/workflows/ci.yml
package.json

ci: run bulloak check

---

.github/workflows/ci.yml
test/smock/MockBFactory.sol
test/smock/MockBToken.sol

perhaps to be ~~merged after~~ supersede #139 ?

ci: ensure smock files are up to date

---

README.md
script/Registry.s.sol

Contract wasn't possible to verify on Sepolia, after redeploy it worked ok.

chore: redeploying testnet

---

README.md
script/Registry.s.sol

- deployed commit is d22ed864d2d1a0cf97e1171fc99467a32a6a75f5

chore: redeployment addresses
